webdocsach/routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\TruyenController;
use App\Http\Controllers\ChapterController;
use App\Http\Controllers\ChapterTranhController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TheloaiController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\InformationController;
use App\Http\Controllers\TruyenTranhController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GoogleDrive;
use App\Http\Controllers\Auth\LoginController;
	


Route::get('/', [IndexController::class,'home']);
Route::get('/danh-muc/{slug}', [IndexController::class,'danhmuc']);
Route::get('/xem-truyen/{slug}', [IndexController::class,'xemtruyen']);
Route::get('/xem-chapter/{slug_truyen}/{slug}', [IndexController::class,'xemchapter']);
Route::get('/kytu/{kytu}', [IndexController::class,'kytu']);
Route::get('/the-loai/{slug}', [IndexController::class,'theloai']);
Route::get('/doc-sach', [IndexController::class,'docsach']);
Route::get('/truyen-tranh', [IndexController::class,'truyentranh']);
Route::get('/xem-truyen-tranh/{slug_truyen}/{slug}', [IndexController::class,'xemtruyentranh']);
Route::get('/tag/{tag}', [IndexController::class,'tag']);
Route::get('/kytu/{kytu}', [IndexController::class,'kytu']);
    
Route::post('/xemsachnhanh', [IndexController::class,'xemsachnhanh']);
Route::post('/truyennoibat', [TruyenController::class,'truyennoibat']);
Route::post('/tim-kiem', [IndexController::class,'timkiem']);
Route::post('/autocomplete-ajax',[IndexController::class,'autocomplete_ajax']);
Route::post('/show-tranh', [IndexController::class,'show_tranh']);
Route::post('/tabs-danhmuc', [IndexController::class,'tabs_danhmuc']);

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('/danhmuc', DanhmucController::class);
Route::resource('/truyen', TruyenController::class);
Route::resource('/sach', SachController::class);
Route::resource('/chapter', ChapterController::class);
Route::resource('/theloai', TheloaiController::class);
Route::resource('/information', InformationController::class);
Route::resource('/truyentranh', TruyenTranhController::class);
Route::resource('/chaptertranh', ChapterTranhController::class);








Route::get('/assignRole/{id}', [HomeController::class, 'assignRole']);
Route::post('/insert_roles/{id}', [HomeController::class, 'insert_roles']);

webdocsach/app/Models/Theloai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Theloai extends Model
{
    use HasFactory;
    public $timestamps = false; //set time to false
    protected $fillable = [
    	'tentheloai', 'mota', 'kichhoat','slug_theloai','tukhoa'
    ];
    protected $primaryKey = 'id';
 	protected $table = 'theloai';

 	public function truyen(){
 		return $this->hasMany('App\Models\Truyen');
 	}
 	public function nhieutheloaitruyen(){
 		return $this->belongsToMany(Truyen::class,'thuocloai','theloai_id','truyen_id');
 	}
}

webdocsach/app/Http/Controllers/TheloaiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Theloai;
use Carbon\Carbon;
class TheloaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $theloai = Theloai::orderBy('id','DESC')->get();
        return view('admincp.theloai.index')->with(compact('theloai'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admincp.theloai.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $data = $request->validate(
            [
                'tentheloai' => 'required|unique:theloai|max:255',
                'slug_theloai' => 'required|unique:theloai|max:255',
                'tukhoa' => 'required|max:255',
                'hinhanh' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048|dimensions:min_width=100,min_height=100,max_width=2000,max_height=2000',
                'mota' => 'required|max:255',
                'kichhoat' => 'required',
            ],
            [
                'slug_theloai.unique' => 'Tên thể loại đã có ,xin điền tên khác',
                'tentheloai.unique' => 'Slug thể loại đã có ,xin điền slug khác',
                'tentheloai.required' => 'Tên thể loại phải có nhé',
                'tukhoa.required' => 'Từ khóa phải có nhé',
                'hinhanh.required' => 'Hình ảnh phải có nhé',
                'mota.required' => 'Mô tả thể loại phải có nhé',
            ]
        );
        // $data = $request->all();
        // dd($data);
        $theloai = new Theloai();
        $theloai->tentheloai = $data['tentheloai'];
        $theloai->tukhoa = $data['tukhoa'];
        $theloai->slug_theloai = $data['slug_theloai'];
        $theloai->mota = $data['mota'];
        $theloai->kichhoat = $data['kichhoat'];
        $theloai->created_at = Carbon::now('Asia/Ho_Chi_Minh');
         //them anh vao folder hinh188.jpg
        $get_image = $request->hinhanh;
        $path = 'public/uploads/theloai/';
        $get_name_image = $get_image->getClientOriginalName();
        $name_image = current(explode('.',$get_name_image));
        $new_image =  $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
        $get_image->move($path,$new_image);
        
        $theloai->hinhanh = $new_image;


        $theloai->save();

        return redirect()->back()->with('status','Thêm thể loại truyện thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $theloai = Theloai::find($id);
        return view('admincp.theloai.edit')->with(compact('theloai'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $data = $request->validate(
            [
                'tentheloai' => 'required|max:255',
                'slug_theloai' => 'required|max:255',
                'tukhoa' => 'required|max:255',

 
                'mota' => 'required|max:255',
                'kichhoat' => 'required',
            ],
            [
                'tukhoa.required' => 'Từ khóa phải có nhé',  
                'tentheloai.required' => 'Tên thể loại phải có nhé',
                'mota.required' => 'Mô tả thể loại phải có nhé',
            ]
        );
        // $data = $request->all();
        // dd($data);
        $theloai = Theloai::find($id);
        $theloai->tentheloai = $data['tentheloai'];
        $theloai->tukhoa = $data['tukhoa'];
        $theloai->slug_theloai = $data['slug_theloai'];
        $theloai->mota = $data['mota'];
        $theloai->kichhoat = $data['kichhoat'];
        $theloai->updated_at = Carbon::now('Asia/Ho_Chi_Minh');
        $get_image = $request->hinhanh;
        if($get_image){

            $path2 = 'public/uploads/theloai/'.$theloai->hinhanh;
            if(file_exists($path2)){
                unlink($path2);
            }
            $path = 'public/uploads/theloai/';
            $get_name_image = $get_image->getClientOriginalName();
            $name_image = current(explode('.',$get_name_image));
            $new_image =  $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
            $get_image->move($path,$new_image);
            
            $theloai->hinhanh = $new_image;
        }
        $theloai->save();

        return redirect()->back()->with('status','Cập nhật thể loại truyện thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $theloai = Theloai::find($id);
        $path = 'public/uploads/theloai/'.$theloai->hinhanh;
            if(file_exists($path)){
                unlink($path);
        }
        $theloai->delete();
        return redirect()->back()->with('status','Xóa thể loại truyện thành công');
    }
}

webdocsach/resources/views/admincp/theloai/create.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Thêm thể loại</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form method="POST" action="{{route('theloai.store')}}" enctype='multipart/form-data'>
                        @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên thể loại</label>
                        <input type="text" class="form-control" value="{{old('tentheloai')}}" onkeyup="ChangeToSlug();" name="tentheloai" id="slug" aria-describedby="emailHelp" placeholder="Tên thể loại">
                        
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Từ khóa</label>
                        <input type="text" class="form-control" value="{{old('tukhoa')}}" name="tukhoa"  aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Slug thể loại</label>
                        <input type="text" class="form-control" value="{{old('slug_theloai')}}" name="slug_theloai" id="convert_slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mô tả</label>
                        <input type="text" class="form-control" value="{{old('mota')}}" name="mota" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Mô tả thể loại">
                        
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Hình ảnh danh mục</label>
                        <input type="file" class="form-control-file" name="hinhanh">
                        
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Kích hoạt</label>
                        <select name="kichhoat" class="custom-select">
                          <option value="0">Kích hoạt</option>
                          <option value="1">Không kích hoạt</option>
                        </select>
                        </div>
                     
                      <button type="submit" name="themtheloai" class="btn btn-primary">Thêm</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

webdocsach/resources/views/admincp/theloai/edit.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Cập nhật thể loại</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form method="POST" action="{{route('theloai.update',[$theloai->id])}}" enctype='multipart/form-data'>
                      @method('PUT')
                        @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên thể loại</label>
                        <input type="text" class="form-control" value="{{$theloai->tentheloai}}" onkeyup="ChangeToSlug();" name="tentheloai" id="slug" aria-describedby="emailHelp" placeholder="Tên thể loại">
                        
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Từ khóa</label>
                        <input type="text" class="form-control" value="{{$theloai->tukhoa}}" name="tukhoa"  aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Slug thể loại</label>
                        <input type="text" class="form-control" value="{{$theloai->slug_theloai}}" name="slug_theloai" id="convert_slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mô tả</label>
                        <input type="text" class="form-control" value="{{$theloai->mota}}" name="mota" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Mô tả thể loại">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Hình ảnh danh mục</label>
                        <input type="file" class="form-control-file" name="hinhanh">
                        <img src="{{asset('public/uploads/theloai/'.$theloai->hinhanh)}}" height="250" width="180">  
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Kích hoạt</label>
                        <select name="kichhoat" class="custom-select">
                          @if($theloai->kichhoat==0)
                          <option selected value="0">Kích hoạt</option>
                          <option value="1">Không kích hoạt</option>
                          @else
                          <option  value="0">Kích hoạt</option>
                          <option selected value="1">Không kích hoạt</option>
                          @endif
                        </select>
                        </div>
                     
                      <button type="submit" name="capnhattheloai" class="btn btn-primary">Cập nhật</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

webdocsach/resources/views/admincp/theloai/index.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Liệt kê thể loại truyện</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Tên</th>
                          <th scope="col">Hình ảnh</th>
                          <th scope="col">Slug</th>
                          <th scope="col">Mô tả</th>
                          <th scope="col">Kích hoạt</th>
                          <th scope="col">Quản lý</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($theloai as $key => $loai)
                        <tr>
                          <th scope="row">{{$key}}</th>
                          <td>{{$loai->tentheloai}}</td>
                          <td>  <img src="{{asset('uploads/theloai/'.$loai->hinhanh)}}" height="250" width="180">  </td>
                          <td>{{$loai->slug_theloai}}</td>
                          <td>{{$loai->mota}}</td>
                          <td>
                              @if($loai->kichhoat==0)
                                <span class="text text-success">Kích hoạt</span> 
                              @else
                                <span class="text text-danger">Không Kích hoạt</span> 
                              @endif

                          </td>
                          <td>
                                <a href="{{route('theloai.edit',[$loai->id])}}" class="btn btn-primary ">Edit</a>

                              <form action="{{route('theloai.destroy',[$loai->id])}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button onclick="return confirm('Bạn muốn xóa thể loại truyện này không?');" class="btn btn-danger">Delete</button>
                                  
                              </form>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection